#application.yml에 spring.profiles.include = oauth로 적용

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 929635782528-m4oo6i54r1qipoq577jl3p3eopsqn0s7.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
            #redirectUri 주소 변경
            RedirectUri: http://localhost:7040/login/oauth2/code/google