server:
  port: 7040
  servlet:
    # default 값
    context-path: /
    encoding:
      enabled: true
      charset: UTF-8
      force: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

spring:
  profiles:
    include: oauth
  datasource:
    url: jdbc:mysql://localhost:5281/infid?characterEncoding=utf8&ServerTimezone=UTC
#    username: root
#    password: sk91xzk33sg.A
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    # hibernate Naming strategies
    physical-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    database: mysql
    show-sql: true
    # create = sessionFactory가 올라갈 때 테이블 지우고 새로 생성
    hibernate:
      ddl-auto: update

  security:
    user:
      name: user
      password: s93kwlsld

         #view 설정
#  mvc:
#    view:
#      # default /templates/(String).mustache
#      prefix: /templates/
#      suffix: .mustache

springdoc:
  packages-to-scan:
    com.lagrange.infi
  swagger-ui:
#    enabled: false
    path: /swagger-ui
    # default url disable
    disable-swagger-default-url: true
  api-docs:
#    enabled: false
    path: /api-docs


