server:
  port: 7040
  servlet:
    encoding:
      charset: UTF-8
      force: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

spring:
  datasource:
    url: jdbc:mysql://localhost:5281/infid?characterEncoding=utf8&ServerTimezone=UTC
    username: root
    password: sk91xzk33sg.A
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create

  security:
    user:
      name: user
      password: s93kwlsld

springdoc:
  packages-to-scan:
    com.lagrange.infi
  swagger-ui:
#    enabled: false
    path: /swagger-ui
    disable-swagger-default-url: true
  api-docs:
#    enabled: false
    path: /api-docs